### ISSUE TITLE
Compute shader shader example doesn't perform compute on mac

### ISSUE THREAD

**Issue by rishflab** [vulkano-rs/vulkano#1127]
*   Version of vulkano: 
```toml
vulkano = "0.11"
vulkano-shaders = "0.11"
vulkano-win = "0.11"
```
*   OS: Mac OS X Mojave
*   GPU (the selected PhysicalDevice): GT750M
*   GPU Driver: Vulkan Instance Version: 1.1.92
*   Upload of a reasonably minimal complete `main.rs` file that demonstrates the issue: 
see basic-compute-shader.rs in the vulkano-examples repository.

# Issue

The example runs but does does not return 12 as expected. Instead it returns 1. The computer shader does not perform the multiply operation.
